version: '3.8'

services:
  cantonese_speech_recognition:
    container_name: cantonese_speech_recognition
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:30000"
    image: wibubunbo/csr:0.0.1

  cantonese_speech_recognition_2:
    container_name: cantonese_speech_recognition_2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30001:30000"
    image: wibubunbo/csr:0.0.1